# Generated by Django 5.0.7 on 2024-09-24 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=9)),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(default=datetime.date(2025, 9, 24))),
                ('income_eligibility', models.BooleanField(default=False)),
                ('interest', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
