# Generated by Django 5.0.7 on 2024-09-25 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='return_date',
            field=models.DateField(default=datetime.date(2025, 9, 25)),
        ),
    ]
